function ax = quickshow(I)

    f = uifigure(...
        "WindowStyle","alwaysontop",...
        "Position",[0 0 500 500],...
        "Visible","off");

    ax = guitools.widgets.ImageAxes(f,...
        "ToolBelt",{'Zoom', 'Colorbar', 'ChooseColormap'},...
        "CData",I,...
        "Units","normalized",...
        "Position",[0 0 1 1],...
        "Colormap",gray);

    movegui(f,"center")

    f.Visible = "on"; % Make the figure visible

end