function ax = quickshow(I,cmap,opts)
    arguments
        I (:,:,:)
        cmap (256,3) double = gray
        opts.Title (1,:) char = 'Untitled'
    end

    f = uifigure(...
        "WindowStyle",          "alwaysontop",...
        "Position",             [0 0 500 500],...
        "Visible",              "off",...
        "AutoResizeChildren",   "off",...
        "Name",                 opts.Title);

    ax = matlabx.ui.widgets.ImageAxes(f,...
        "ToolBelt",             {'Zoom', 'Colorbar', 'ChooseColormap'},...
        "CData",                I,...
        "Units",                "normalized",...
        "Position",             [0 0 1 1],...
        "Colormap",             cmap,...
        "Name",                 "Viewer");

    movegui(f,"center")

    f.Visible = "on"; % Make the figure visible

end